export const constants = {
  BORDERS: 26,
  CHARACTER_WIDTH: 104,
  START_BALLS_Y: 200,
  BOTTOM_BORDER: 100,
  TOP_BORDER: 140,
  INIT_FALLING_SPEED: 20,
  INIT_FALLING_FREQUENCY: 1000,
  INIT_PLAYER_SPEED: 1,
  INIT_GAME_TIME: 60
};




